// TODO: all icons should be restructured the way it's done in geometrics icons

// geometrics
export { default as IconGeometricRectangle } from '@/components/icons/geometrics/IconGeometricRectangle'
export { default as IconGeometricRightAngle } from '@/components/icons/geometrics/IconGeometricRightAngle'
export { default as IconGeometricThreeHorizontalLines } from '@/components/icons/geometrics/IconGeometricThreeHorizontalLines'
export { default as IconGeometricThreeVerticalLines } from '@/components/icons/geometrics/IconGeometricThreeVerticalLines'
export { default as IconGeometricTwoRectangles } from '@/components/icons/geometrics/IconGeometricTwoRectangles'
export { default as IconGeometricTwoRotatedRectangles } from '@/components/icons/geometrics/IconGeometricTwoRotatedRectangles'
//
export { default as IconArrowLeft } from '@/components/icons/IconArrowLeft'
export { default as IconArrowTopRight } from '@/components/icons/IconArrowTopRight'
export { default as IconBell } from '@/components/icons/IconBell'
export { default as IconCheck } from '@/components/icons/IconCheck'
export { default as IconCheckCircle } from '@/components/icons/IconCheckCircle'
export { default as IconCheckCircleAlt } from '@/components/icons/IconCheckCircleAlt'
export { default as IconCheckCircleAltDim } from '@/components/icons/IconCheckCircleAltDim'
export { default as IconClock } from '@/components/icons/IconClock'
export { default as IconClose } from '@/components/icons/IconClose'
export { default as IconCross } from '@/components/icons/IconCross'
export { default as IconDecorativeLines } from '@/components/icons/IconDecorativeLines'
export { default as IconECTS } from '@/components/icons/IconECTS'
export { default as IconEmail } from '@/components/icons/IconEmail'
export { default as IconEmblem } from '@/components/icons/IconEmblem'
export { default as IconInfoFRDO } from '@/components/icons/IconInfoFRDO'
export { default as IconLoader } from '@/components/icons/IconLoader'
export { default as IconLocation } from '@/components/icons/IconLocation'
export { default as IconLogo } from '@/components/icons/IconLogo'
export { default as IconLogoTitle } from '@/components/icons/IconLogoTitle'
export { default as IconMessages } from '@/components/icons/IconMessages'
export { default as IconMobilePhone } from '@/components/icons/IconMobilePhone'
export { default as IconMoreThan } from '@/components/icons/IconMoreThan'
export { default as IconPaperCorner } from '@/components/icons/IconPaperCorner'
export { default as IconPhoneAlt } from '@/components/icons/IconPhoneAlt'
export { default as IconQuote } from '@/components/icons/IconQuote'
export { default as IconRosObrInsignia } from '@/components/icons/IconRosObrInsignia'
export { default as IconScreen } from '@/components/icons/IconScreen'
export { default as IconSearch } from '@/components/icons/IconSearch'
export { default as IconSpinner } from '@/components/icons/IconSpinner'
export { default as IconTelegram } from '@/components/icons/IconTelegram'
export { default as IconTelegramAlt } from '@/components/icons/IconTelegramAlt'
export { default as IconTriangleBottom } from '@/components/icons/IconTriangleBottom'
export { default as IconViber } from '@/components/icons/IconViber'
export { default as IconVk } from '@/components/icons/IconVk'
export { default as IconWhatsapp } from '@/components/icons/IconWhatsapp'
export { default as IconWhatsappAlt } from '@/components/icons/IconWhatsappAlt'
