export const SET_JOURNAL_CATEGORIES = 'SET_JOURNAL_CATEGORIES'
export const SET_JOURNAL_TAGS = 'SET_JOURNAL_TAGS'
export const SET_JOURNAL_ARTICLES = 'SET_JOURNAL_ARTICLES'
export const SET_JOURNAL_ARTICLES_ARTICLE = 'SET_JOURNAL_ARTICLES_ARTICLE'
export const SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY =
  'SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY'
export const SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY_TAG =
  'SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY_TAG'
export const SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY_TAG_ARTICLE =
  'SET_GSP_CONTEXT_PARAMS_JOURNAL_CATEGORY_TAG_ARTICLE'
export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const OPEN_OVERLAY = 'OPEN_OVERLAY'
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY'
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY'
export const SET_PROGRAMS = 'SET_PROGRAMS'
export const SET_PROGRAM = 'SET_PROGRAM'
export const SET_CUR_PROGRAMS_TYPE = 'SET_CUR_PROGRAMS_TYPE'
export const SET_CUR_STUDY_FIELD = 'SET_CUR_STUDY_FIELD'
export const SET_CUR_PROGRAMS_STUDY_FIELD_SLUG =
  'SET_CUR_PROGRAMS_STUDY_FIELD_SLUG'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SEARCH_PROGRAM = 'SEARCH_PROGRAM'
